-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 21:04:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestaoLoja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestaoLoja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestaoLoja` DEFAULT CHARACTER SET utf8 ;
USE `gestaoLoja` ;

-- -----------------------------------------------------
-- Table `gestaoLoja`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `NIF` INT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `sexo` ENUM('Masculino', 'Femino') NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Pessoa_idPessoa`),
  INDEX `fk_Cliente_Pessoa_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Cliente_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `gestaoLoja`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `salario` FLOAT NULL,
  `estado` VARCHAR(50) NULL,
  `dataNascimento` DATE NULL,
  `serieCarteira` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Pessoa_idPessoa`),
  INDEX `fk_Vendedor_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  UNIQUE INDEX `serieCarteira_UNIQUE` (`serieCarteira` ASC),
  CONSTRAINT `fk_Vendedor_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `gestaoLoja`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`, `Pessoa_idPessoa`),
  INDEX `fk_Fornecedor_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Fornecedor_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `gestaoLoja`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `ilha` VARCHAR(45) NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `Funcionario_idFuncionario`),
  INDEX `fk_Endereco_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Endereco_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `gestaoLoja`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Material` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `unidadeMedida` VARCHAR(45) BINARY NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Venda` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `preco` FLOAT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Cliente_idCliente`, `Funcionario_idFuncionario`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `gestaoLoja`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `gestaoLoja`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL,
  `valor` FLOAT NULL,
  `Material_idMaterial` INT NOT NULL,
  `Venda_idVenda` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Material_idMaterial`, `Venda_idVenda`),
  INDEX `fk_Pedido_Material1_idx` (`Material_idMaterial` ASC),
  INDEX `fk_Pedido_Venda1_idx` (`Venda_idVenda` ASC),
  CONSTRAINT `fk_Pedido_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `gestaoLoja`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `gestaoLoja`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaoLoja`.`utilizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestaoLoja`.`utilizador` ;

CREATE TABLE IF NOT EXISTS `gestaoLoja`.`utilizador` (
  `idutilizador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idutilizador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
